# Generated by Django 4.2.16 on 2024-10-02 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_family_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_family_members', to='ict.userlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='ict.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_code', models.CharField(max_length=255)),
                ('pill_name', models.CharField(max_length=255)),
                ('confidence', models.CharField(max_length=255)),
                ('efficacy', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('usage', models.TextField()),
                ('precautions_before_use', models.TextField()),
                ('usage_precautions', models.TextField()),
                ('drug_food_interactions', models.TextField()),
                ('side_effects', models.TextField()),
                ('storage_instructions', models.TextField()),
                ('pill_image', models.TextField()),
                ('pill_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_category_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_code', models.CharField(max_length=255)),
                ('pill_name', models.CharField(max_length=255)),
                ('confidence', models.CharField(max_length=255)),
                ('predicted_category_id', models.IntegerField(blank=True, null=True)),
                ('efficacy', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('usage', models.TextField()),
                ('precautions_before_use', models.TextField()),
                ('usage_precautions', models.TextField()),
                ('drug_food_interactions', models.TextField()),
                ('side_effects', models.TextField()),
                ('storage_instructions', models.TextField()),
                ('pill_image', models.TextField()),
                ('pill_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Sear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_code', models.CharField(max_length=255)),
                ('pill_name', models.CharField(max_length=255)),
                ('confidence', models.CharField(max_length=255)),
                ('efficacy', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('usage', models.TextField()),
                ('precautions_before_use', models.TextField()),
                ('usage_precautions', models.TextField()),
                ('drug_food_interactions', models.TextField()),
                ('side_effects', models.TextField()),
                ('storage_instructions', models.TextField()),
                ('pill_image', models.TextField()),
                ('pill_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='SentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_code', models.CharField(max_length=100)),
                ('pill_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
