# Generated by Django 4.2.16 on 2024-10-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0002_family_familymember2_favorite_record_sear_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember2',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
