# Generated by Django 4.2.16 on 2024-10-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0003_familymember2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember2',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='familymember2',
            name='name',
        ),
        migrations.AlterField(
            model_name='familymember2',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember2',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_of', to='ict.userlist'),
        ),
        migrations.AlterField(
            model_name='familymember2',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
