# Generated by Django 4.2.16 on 2024-10-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0007_record_predicted_category_id_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='predicted_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
